apiVersion: v1
kind: Service
metadata:
  name: axon-server
  namespace: saga-pattern
spec:
  selector:
    app: axon-server
  ports:
    - name: http
      port: 8024
      targetPort: 8024
    - name: grpc
      port: 8124
      targetPort: 8124
  clusterIP: None  # headless — required for StatefulSet DNS
